services:
  - type: web
    name: friendmap-api
    runtime: node
    rootDir: apps/api
    plan: free
    buildCommand: npm ci --legacy-peer-deps && DATABASE_URL="postgresql://user:pass@localhost:5432/db" npx prisma generate && npm run build
    startCommand: NODE_ENV=production npx prisma migrate deploy && NODE_ENV=production npm run start:prod
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: SEED_DEMO
        value: "true"
      - key: REDIS_TLS
        value: "true"
      - key: UPLOADS_DIR
        value: /tmp/uploads
      - key: CORS_ORIGINS
        value: https://majdabbassi.github.io
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false